name: Build Rocket

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      # ===== WINDOWS PACKAGE =====
      - name: Package Windows
        if: matrix.os == 'windows-latest'
        run: |
          mkdir package
          copy build\Release\rocket.t.exe package\
          xcopy assets package\assets\ /E /I
          powershell Compress-Archive -Path package\* -DestinationPath rocket-windows.zip

      # ===== LINUX PACKAGE =====
      - name: Package Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir package
          cp build/rocket.t package/
          cp -r assets package/
          zip -r rocket-linux.zip package

      # ===== MAC PACKAGE =====
      - name: Package macOS
        if: matrix.os == 'macos-latest'
        run: |
          mkdir package
          cp build/rocket.t package/
          cp -r assets package/
          zip -r rocket-macos.zip package

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rocket-windows.zip
            rocket-linux.zip
            rocket-macos.zip